[package]
name = "console_fb"
version = "0.1.0"
authors = ["140bpmdubstep <laineprikol@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.5"
[lib]
crate-type = ["lib"]